config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def  index
		@employees = Employee.all
	end

	def new
		@employee = Employee.new
	end

	def create
		@employee = Employee.new(params.require(:employee).permit(:name, :age))

		if @employee.save
			redirect_to employees_path
		else
			render :new
		end
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])

		@employee.update_attributes!(name: params[:employee][:name], age: params[:employee][:age])

		if @employee.save
			redirect_to employees_path
		else
			redirect_to edit_employee_path(@employee.id)
		end
	end

	def destroy
		@employee = Employee.find(params[:id])

		if @employee.destroy
			redirect_to employees_path
		else
			redirect_to employees_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<%= form_for @employee do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :age %>
	<%= f.text_field :age %>

	<%= f.submit 'Update' %>
<% end %>

app/views/employees/index.html.erb
<%= link_to 'New Employee', new_employee_path %>
<table>

	<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Edit</th>
		<th>Destroy</th>
	</tr>

	<% @employees.each do |employee| %>
		<tr>
			<td><%= employee.name %></td>
			<td> <%= employee.age %></td>
			<td><%= link_to 'Edit', edit_employee_path(employee.id) %></td>
			<td><%= link_to 'Delete', {action: 'destroy', id: employee.id}, method: 'delete', data: {confirm: 'Are you sure you want to delete?'} %></td>
		</tr>
	<% end %>
</table>

app/views/employees/new.html.erb
<%= form_for @employee do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :age %>
	<%= f.text_field :age %>

	<%= f.submit 'Create' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>